In [1]:
import numpy as np
import matplotlib.pyplot as plt
import log_bessel as lb
from scipy.integrate import quad, fixed_quad

# TESTS

In [2]:
v_to_test = np.array([0,3.15e-7, 2.62e-6, 1.3e-5, 9.2e-5, 0.0026,
                      0.0843, 0.17345, 1, 1.63, 7.42, 42.42424, 86.5,
                      113.8, 148.7565, 180.6, 246.3, 300.5, 513.6,
                      712.456, 714.456, 1235.6,8656, 15330.75,
                      37634.2 ,85323])

z_to_test = np.array([1.48e-7, 3.6e-6, 7.248e-5, 4.32e-4, 8.7e-3, 0.04523, 0.17532,
                      1, 3, 11.32465, 105.6, 1038.4, 4236, 11457.6, 62384, 105321.6,
                      158742.3, 196754,  1.98e6])

In [49]:
def logdiffexp(x1,x2):
    
    return x1+np.log1p(-np.exp(-(x1-x2)))

def forward_recursion(v,z):
    
    first, _ = lb.log_bessel_k(v+2,z)
    second = np.log(2) + np.log(v+1) - np.log(z) + lb.log_bessel_k(v+1,z)[0]
    indeces = lb.log_bessel_k(v+1,z)[1]
    
    display(first)
    display(second)
    display(v+1)
    
    return logdiffexp(first,second), indeces

def backward_recursion(v, z):
    
    first, indeces = lb.log_bessel_k(v-2, z)
    second = np.log(2)+np.log(v-1)-np.log(z)+lb.log_bessel_k(v-1, z)[0]
    
    return np.logaddexp(first, second), indeces

def recursion_test(v, z):
    
    rhs = np.zeros(np.shape(v))
    
    i_forward = v <= 1.
    i_backward = v > 1.
    
    rhs[i_forward], indices_forward = forward_recursion(v[i_forward], z)
    rhs[i_backward], indices_backward = backward_recursion(v[i_backward], z)
    
    #print(rhs[i_forward])
    
    lhs = lb.log_bessel_k(v, z)[0]
    
    return lhs/rhs, indices_forward, indices_backward

In [50]:
ratio, i_forw, i_back = recursion_test(v_to_test, z_to_test[0])

/home/jacob/Uni/Pulsar_timing/log_bessel.py:125: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  integral[i] = quad(f,0,np.inf,args=(v_tmp, z, value_at_max[i]))[0]
/home/jacob/Uni/Pulsar_timing/log_bessel.py:127: RuntimeWarning: invalid value encountered in log
  return np.log(integral)+value_at_max


array([-1.38621756, -1.38621574, -1.38620114, -1.38613342, -1.38561658,
       -1.36921258, -0.83392572, -0.24761594, 49.25760223])

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan, 15.72613036])

array([1.        , 1.00000032, 1.00000262, 1.000013  , 1.000092  ,
       1.0026    , 1.0843    , 1.17345   , 2.        ])

/home/jacob/Uni/Pulsar_timing/log_bessel.py:125: IntegrationWarning: The algorithm does not converge.  Roundoff error is detected
  in the extrapolation table.  It is assumed that the requested tolerance
  cannot be achieved, and that the returned result (if full_output = 1) is 
  the best which can be obtained.
  integral[i] = quad(f,0,np.inf,args=(v_tmp, z, value_at_max[i]))[0]
/home/jacob/Uni/Pulsar_timing/log_bessel.py:205: RuntimeWarning: divide by zero encountered in log
  trap_1 = np.log(v) < (asymp_v_slope * np.log(z) + asymp_v_intercept)
/home/jacob/Uni/Pulsar_timing/log_bessel.py:206: RuntimeWarning: divide by zero encountered in log
  trap_2 = np.log(v) > (asymp_z_slope * np.log(z) + asymp_z_intercept)


In [99]:
v_gg = 1
z_gg = z_to_test[0]

display(z_gg)

t_max = lb.log_gamma_integral_max_t(v_gg, z_gg)
display(t_max)
value_at_max = lb.log_gamma_integral_func(t_max, v_gg, z_gg)
display(value_at_max)

def f(t, v, z, val_max):

    log_value = lb.log_gamma_integral_func(t, v, z, val_max)

    return 0.5 * np.exp(log_value)

quad(f, 0, np.inf, args=(v_gg, z_gg, value_at_max), epsabs=0)[0]

1.48e-07

0.9992554201505217

-1.4800004105610682e-07

/home/jacob/anaconda3/envs/pulsar_timing/lib/python3.7/site-packages/ipykernel_launcher.py:17: IntegrationWarning: The integral is probably divergent, or slowly convergent.


-0.5000005638655747